port: 8080

dynamodb:
  tablePictureProcess:
    name: pictureProcess
    primaryKeyName: Origin
    primaryKeyType: S
    sortKeyName: ID
    sortKeyType: B
  tablePictureValidation:
    name: pictureValidation
    primaryKeyName: Origin
    primaryKeyType: S
    sortKeyName: ID
    sortKeyType: B
  tablePictureProduction:
    name: pictureProduction
    primaryKeyName: Origin
    primaryKeyType: S
    sortKeyName: ID
    sortKeyType: B
  tablePictureBlocked:
    name: pictureBlocked
    primaryKeyName: Origin
    primaryKeyType: S
    sortKeyName: ID
    sortKeyType: B
  tableTag:
    name: tag
    primaryKeyName: Type
    primaryKeyType: S
    sortKeyName: ID
    sortKeyType: B
  tableUser:
    name: user
    primaryKeyName: Origin
    primaryKeyType: S
    sortKeyName: ID
    sortKeyType: B

buckets:
  picture:
    name: picture