dynamodbTablePictureProcess:
  TablePictureProcessName: scraperPictureProcess
  TablePicturePK: Origin
  TablePictureSK: ID
dynamodbTablePictureValidation:
  TablePictureValidationName: scraperPictureValidation
  TablePictureValidationPK: Origin
  TablePictureValidationSK: ID
dynamodbTablePictureProduction:
  TablePictureProductionName: scraperPictureProduction
  TablePictureProductionPK: Origin
  TablePictureProductionSK: ID
dynamodbTablePictureBlocked:
  TablePictureBlockedName: scraperPictureBlocked
  TablePictureBlockedPK: Origin
  TablePictureBlockedSK: ID
dynamodbTableTag:
  TableTagName: scraperTag
  TableTagPK: Type
  TableTagSK: ID
dynamodbTableUser:
  TableUserName: scraperUser
  TableUserPK: Origin
  TableUserSK: ID