dynamodb:
  tablePictureProcess:
    name: pictureProcess
    primaryKey: Origin
    sortKey: ID
  tablePictureValidation:
    name: pictureValidation
    primaryKey: Origin
    sortKey: ID
  tablePictureProduction:
    name: pictureProduction
    primaryKey: Origin
    sortKey: ID
  tablePictureBlocked:
    name: pictureBlocked
    primaryKey: Origin
    sortKey: ID
  tableTag:
    name: tag
    primaryKey: Type
    sortKey: ID
  tableUser:
    name: user
    primaryKey: Origin
    sortKey: ID