TABLE_PICTURE_PROCESS_NAME: scraperPictureProcess
TABLE_PICTURE_VALIDATION_NAME: scraperPictureValidation
TABLE_PICTURE_PRODUCTION_NAME: scraperPictureProduction
TABLE_PICTURE_BLOCKED_NAME: scraperPictureBlocked
TABLE_PICTURE_PK: Origin
TABLE_PICTURE_SK: Name
TABLE_TAG_NAME: scraperTag
TABLE_TAG_PK: Type
TABLE_TAG_SK: Name
TABLE_USER_NAME: scraperUser
TABLE_USER_PK: Origin
TABLE_USER_SK: Name