dynamodb:
  tablePictureProcess:
    name: pictureProcess
    primaryKeyName: Origin
    primaryKeyType: S
    sortKeyName: ID
    sortKeyType: S
  tablePictureValidation:
    name: pictureValidation
    primaryKeyName: Origin
    primaryKeyType: S
    sortKeyName: ID
    sortKeyType: S
  tablePictureProduction:
    name: pictureProduction
    primaryKeyName: Origin
    primaryKeyType: S
    sortKeyName: ID
    sortKeyType: S
  tablePictureBlocked:
    name: pictureBlocked
    primaryKeyName: Origin
    primaryKeyType: S
    sortKeyName: ID
    sortKeyType: S
  tableTag:
    name: tag
    primaryKeyName: Type
    primaryKeyType: S
    sortKeyName: ID
    sortKeyType: S
  tableUser:
    name: user
    primaryKeyName: Origin
    primaryKeyType: S
    sortKeyName: ID
    sortKeyType: S