name: Container

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [master]

env:
  COMMON_NAME: ${{ github.sha }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_PROFILE: ${{ vars.AWS_PROFILE }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  GH_ORG: KookaS
  GH_REPO: infrastructure-modules
  GH_BRANCH: dynamodb
  GH_SCRIPT_PATH: .github/workflows

jobs:
  ecr:
    name: setup ECR
    runs-on: ubuntu-latest
    environment: KookaS
    env:
      AWS_CLI_SERVICE: ecr  # private
      DOCKER_FOLDER_PATH: Dockerfile
      IMAGE_TAG: "latest"
      SCRIPT_NAME: ecr-setup.sh
      LOG_FILE: log.out
      GH_REPO_PATH: https://raw.githubusercontent.com/$GH_ORG/$GH_REPO/$GH_BRANCH
    outputs:
      IMAGE_TAG: ${{ steps.get-output.outputs.IMAGE_TAG }}
      ECR_LOGIN_PASSWORD: ${{ steps.get-output.outputs.ECR_LOGIN_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: setup AWS CLI
      #   run: |
      #     aws --version
      #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
      #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
      #     aws configure set region $AWS_REGION

      # - name: Get ECR login password
      #   id: get-login-password
      #   run: |
      #     if [[ $AWS_CLI_SERVICE == ecr ]]; then
      #       echo "ECR_LOGIN_PASSWORD=$(aws ecr get-login-password --region $AWS_REGION)" >> $GITHUB_OUTPUT
      #     elif [[ $AWS_CLI_SERVICE == ecr-public ]]; then
      #       
      #     fi

      # - name: login to ECR  IMAGE_TAG: "latest"
      #   run: |
      #     if [[ $AWS_CLI_SERVICE == ecr ]]; then
      #       docker login --username AWS --password ${{ steps.get-login-password.outputs.ECR_LOGIN_PASSWORD }} $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      #     elif [[ $AWS_CLI_SERVICE == ecr-public ]]; then
      #       docker login --username AWS --password ${{ steps.get-login-password.outputs.ECR_LOGIN_PASSWORD }} public.ecr.aws
      #     fi
      
      # - name: Create ECR repository
      #   run: |
      #     aws ecr create-repository \
      #       --repository-name $COMMON_NAME \
      #       --image-scanning-configuration scanOnPush=true \
      #       --region $AWS_REGION \
      #       --output text \
      #       --query 'repository.repositoryUri'

      # - name: Build, tag, and push image to Amazon ECR
      #   id: build-image
      #   env:
      #     
      #   run: |
      #     export ECR_URI=$(aws ecr describe-repositories --repository-names $COMMON_NAME --output text --query "repositories[].[repositoryUri]")
      #     echo "ECR_URI= $ECR_URI"
      #     docker build -t $ECR_URI/$IMAGE_TAG -f $DOCKER_FOLDER_PATH .
      #     docker tag $(docker images -q $ECR_URI/$IMAGE_TAG) $ECR_URI:$IMAGE_TAG
      #     docker push $ECR_URI:$IMAGE_TAG
      #     
      - name: run ECR-setup
        id: script
        run: |
          # curl -o $SCRIPT_NAME https://raw.githubusercontent.com/KookaS/infrastructure-modules/dynamodb/.github/workflows/ecr-create.sh?token=GHSAT0AAAAAACCEOEUUZDBFTBEZS66QJV2OZDS4JMA \
          chmod +x $SCRIPT_NAME

          ./$SCRIPT_NAME LOG_FILE=$LOG_FILE ECR_CREATE=false AWS_ACCESS_KEY=$AWS_ACCESS_KEY AWS_SECRET_KEY=$AWS_SECRET_KEY AWS_REGION=$AWS_REGION AWS_ACCOUNT_ID=$AWS_ACCOUNT_ID AWS_CLI_SERVICE=ecr COMMON_NAME=$COMMON_NAME IMAGE_TAG=$IMAGE_TAG DOCKER_FOLDER_PATH=$DOCKER_FOLDER_PATH

          echo LOGS: && cat $LOG_FILE
          # echo ERRORS:
          # grep -ni error $LOG_FILE | sed 's/$/\n/'
          # if [ -n "$(grep -i error $LOG_FILE)" ]; then
          #   echo "Errors found"
          #   # exit 10
          # fi
          # echo "No errors found"

      - name: Get ECR login password
        id: get-output
        run: |
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          if [[ $AWS_CLI_SERVICE == ecr ]]; then
            echo "ECR_LOGIN_PASSWORD=$(aws ecr get-login-password --region $AWS_REGION)" >> $GITHUB_OUTPUT
          elif [[ $AWS_CLI_SERVICE == ecr-public ]]; then
            echo "ECR_LOGIN_PASSWORD=$(aws ecr-public get-login-password --region $AWS_REGION)" >> $GITHUB_OUTPUT
          fi
          

  # Container network where we can access with the service name and the port
  localstack:
    name: Container check localstack
    needs: [ecr]
    runs-on: ubuntu-latest
    container: ubuntu # connect the workflow steps to the network
    environment: KookaS
    env:
      AWS_REGION: us-east-1
      AWS_PROFILE: dummy
      AWS_ACCESS_KEY: dummy
      AWS_SECRET_KEY: dummy
    services:
      local-cloud:
        image: localstack/localstack
      local-project:
        image:  ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ github.sha }}:${{ needs.ecr.outputs.IMAGE_TAG }}
        credentials:
          username: AWS
          password: ${{ needs.ecr.outputs.ECR_LOGIN_PASSWORD }}
        env:
          CLOUD_HOST: localstack
          LOCALSTACK_URI: http://local-cloud:4566
          COMMON_NAME: ${{ github.sha }}
          FLICKR_PRIVATE_KEY: 123
          FLICKR_PUBLIC_KEY: 123
          UNSPLASH_PRIVATE_KEY: 123
          UNSPLASH_PUBLIC_KEY: 123
          PEXELS_PUBLIC_KEY: 123
          AWS_REGION: $AWS_REGION
          AWS_ACCESS_KEY: $AWS_ACCESS_KEY
          AWS_SECRET_KEY: $AWS_SECRET_KEY

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup
        id: setup
        run: |
          apt update -qq
          apt install curl unzip wget -y -qq
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -qq awscliv2.zip
          ./aws/install
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64  -qq -O /usr/bin/yq
          chmod +x /usr/bin/yq
          echo "PORT=$(yq eval '.port' config/config.yml)" >> $GITHUB_OUTPUT

      - name: setup AWS CLI
        run: |
          aws --version
          aws configure set aws_access_key_id $AWS_ACCESS_KEY
          aws configure set aws_secret_access_key $AWS_SECRET_KEY
          aws configure set region $AWS_REGION

      - name: Status localstack
        run: |
          curl -Is http://local-cloud:4566 | grep HTTP
      - name: Status localstack table
        run: |
          aws dynamodb list-tables --endpoint-url=http://local-cloud:4566 --region=us-east-1
      - name: Status root
        run: |
          curl -Is http://local-project:${{ steps.setup.outputs.PORT }}/ | grep HTTP
      - name: Status healthz
        run: |
          curl -Is http://local-project:${{ steps.setup.outputs.PORT }}/healthz | grep HTTP

  dynamodb:
    name: Container check dynamodb
    needs: [ecr]
    runs-on: ubuntu-latest
    container: ubuntu # connect the workflow steps to the network
    environment: KookaS
    services:
      local-project:
        image:  ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ github.sha }}:${{ needs.ecr.outputs.IMAGE_TAG }}
        credentials:
          username: AWS
          password: ${{ needs.ecr.outputs.ECR_LOGIN_PASSWORD }}
        env:
          CLOUD_HOST: aws
          COMMON_NAME: ${{ github.sha }}
          FLICKR_PRIVATE_KEY: 123
          FLICKR_PUBLIC_KEY: 123
          UNSPLASH_PRIVATE_KEY: 123
          UNSPLASH_PUBLIC_KEY: 123
          PEXELS_PUBLIC_KEY: 123
          AWS_REGION: $AWS_REGION
          AWS_ACCESS_KEY: $AWS_ACCESS_KEY
          AWS_SECRET_KEY: $AWS_SECRET_KEY

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        id: setup
        run: |
          apt update -qq
          apt install curl unzip wget -y -qq
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip -qq awscliv2.zip
          ./aws/install
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64  -qq -O /usr/bin/yq
          chmod +x /usr/bin/yq
          echo "PORT=$(yq eval '.port' config/config.yml)" >> $GITHUB_OUTPUT          

      - name: setup AWS CLI
        run: |
          aws --version
          aws configure set aws_access_key_id $AWS_ACCESS_KEY
          aws configure set aws_secret_access_key $AWS_SECRET_KEY
          aws configure set region $AWS_REGION

      - name: create tables
        shell: bash
        run: |
          names=($(yq eval '.dynamodb.*.name' config/config.yml))
          primaryKeyNames=($(yq eval '.dynamodb.*.primaryKeyName' config/config.yml))
          primaryKeyTypes=($(yq eval '.dynamodb.*.primaryKeyType' config/config.yml))
          sortKeyNames=($(yq eval '.dynamodb.*.sortKeyName' config/config.yml))
          sortKeyTypes=($(yq eval '.dynamodb.*.sortKeyType' config/config.yml))
          i=0
          for _ in $(yq eval '.dynamodb.*.name' config/config.yml)
          do
            aws dynamodb create-table \
              --region $AWS_REGION \
              --table-name $COMMON_NAME-${names[$i]} \
              --attribute-definitions AttributeName=${primaryKeyNames[$i]},AttributeType=${primaryKeyTypes[$i]} AttributeName=${sortKeyNames[$i]},AttributeType=${sortKeyTypes[$i]}\
              --key-schema AttributeName=${primaryKeyNames[$i]},KeyType=HASH AttributeName=${sortKeyNames[$i]},KeyType=RANGE \
              --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5
            i=$((i+1))
          done

      - name: Status dynamodb table
        run: |
          tables=$(aws dynamodb list-tables --region=$AWS_REGION --query 'TableNames[?starts_with(@, `'$COMMON_NAME'`)]')
          if [ "$tables" = "[]" ]; then exit 1; fi
      - name: Status root
        run: |
          curl -Is http://local-project:${{ steps.setup.outputs.PORT }}/ | grep HTTP
      - name: Status healthz
        run: |
          curl -Is http://local-project:${{ steps.setup.outputs.PORT }}/healthz | grep HTTP

  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    needs: [ecr, localstack, dynamodb]
    if: ${{ always() && contains(join(needs.ecr.result, ','), 'success') }}
    environment: KookaS
    env:
      AWS_CLI_SERVICE: ecr  # private
    outputs:
      IMAGE_TAG: ${{ steps.build-image.outputs.IMAGE_TAG }}
      ECR_LOGIN_PASSWORD: ${{ steps.get-login-password.outputs.ECR_LOGIN_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup AWS CLI
        run: |
          aws --version
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          aws configure set region $AWS_REGION

      - name: login to ECR
        run: |
          if [[ $AWS_CLI_SERVICE == ecr ]]; then
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
          elif [[ $AWS_CLI_SERVICE == ecr-public ]]; then
            aws ecr-public get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin public.ecr.aws
          fi
      
      - name: Delete ECR repository
        run: |
          aws ecr delete-repository \
            --repository-name $COMMON_NAME \
            --force \
            --region $AWS_REGION \
            --output text \
            --query 'repository.registryId'

      - name: Delete Dynamodb tables
        if: ${{ always() && contains(join(needs.dynamodb.result, ','), 'success') }}
        shell: bash
        run: |
          names=($(yq eval '.dynamodb.*.name' config/config.yml))
          primaryKeyNames=($(yq eval '.dynamodb.*.primaryKeyName' config/config.yml))
          primaryKeyTypes=($(yq eval '.dynamodb.*.primaryKeyType' config/config.yml))
          sortKeyNames=($(yq eval '.dynamodb.*.sortKeyName' config/config.yml))
          sortKeyTypes=($(yq eval '.dynamodb.*.sortKeyType' config/config.yml))
          i=0
          for _ in $(yq eval '.dynamodb.*.name' config/config.yml)
          do
            aws dynamodb delete-table \
              --region $AWS_REGION \
              --table-name $COMMON_NAME-${names[$i]}
            i=$((i+1))
          done
