name: ECR helper

on:
  workflow_dispatch:
    inputs:
      aws-service:
        description: 'service'
        required: true
        type: choice
        options: 
        - ecr
        - ecr-public
      aws-account_name:
        description: 'AWS Account name, default github account name'
        required: true
        type: string
      aws-account-id:
        description: 'AWS Account ID'
        required: true
        type: string
      aws-region:
        description: 'AWS Region to launch the instance'
        required: true
        type: string
      access-key:
        description: 'AWS Region to launch the instance'
        required: true
        type: string
      secret-key:
        description: 'AWS Region to launch the instance'
        required: true
        type: string
      docker-path:
        description: 'The path to the folder where the file exists'
        required: true
        type: string
      ecr-repository-name:
        description: 'The name of the repository'
        required: true
        type: string
      keep-images-amount:
        description: 'The path to the docker file'
        type: string

env:
  AWS_CLI_SERVICE: ${{ inputs.aws-service }}
  AWS_ACCOUNT_NAME: ${{ inputs.aws-account_name }}
  AWS_ACCOUNT_ID: ${{ inputs.aws-account-id }}
  AWS_REGION: ${{ inputs.aws-region }}
  AWS_ACCESS_KEY_ID: ${{ inputs.access-key }}
  AWS_SECRET_ACCESS_KEY: ${{ inputs.secret-key }}
  DOCKER_PATH: ${{ inputs.docker-path }}
  ECR_REPOSITORY: ${{ inputs.ecr-repository-name }}
  KEEP_IMAGES_AMOUNT: ${{ inputs.keep-images-amount }}
  POLICY_FILE_NAME: "temp-file"

jobs:
  ecr:
    name: Publish image on ECR
    runs-on: ubuntu-latest

    steps:
      - name: Reusable ECR workflow
        uses: KookaS/scraper-backend/.github/workflows/ecr.yml
        with:
          aws-service: $AWS_CLI_SERVICE
          aws-account_name: $AWS_ACCOUNT_NAME
          aws-account-id: $AWS_ACCOUNT_ID
          aws-region: $AWS_REGION
          # access-key: $AWS_ACCESS_KEY_ID
          # secret-key: $AWS_SECRET_ACCESS_KEY
          docker-path: $ECR_REPOSITORY
          ecr-repository-name: $KEEP_IMAGES_AMOUNT
          keep-images-amount: $POLICY_FILE_NAME

