# name: Test container

# on:
#   push:
#     branches: [master]
#   pull_request:
#     types: [opened, edited, synchronize, reopened]

# jobs:
#   healthz:
#     name: Check endpoints
#     runs-on: ubuntu-latest
#     services:
#       localstack:
#         image: localstack/localstack
#         ports:
#           - 4566:4566
#       scraper-backend:
#         image: scraper-backend  # no image yet
#         ports:
#           - 8080:8080
#         env:
#           AWS_ACCESS_KEY_ID: 123
#           AWS_SECRET_ACCESS_KEY: 123
#           CLOUD_HOST: localstack
#           LOCALSTACK_URI: http://localhost:4566
#           COMMON_NAME: scraper-backend-test
#           FLICKR_PRIVATE_KEY: 123
#           FLICKR_PUBLIC_KEY: 123
#           UNSPLASH_PRIVATE_KEY: 123
#           UNSPLASH_PUBLIC_KEY: 123
#           PEXELS_PUBLIC_KEY: 123
#           AWS_REGION: us-west-1
#           AWS_PROFILE: dummy
#           AWS_ACCESS_KEY: dummy
#           AWS_SECRET_KEY: dummy

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       - name: Check health path
#         run: |-
#           curl \
#             --fail \
#             --silent \
#             --show-error \
#             --location \
#             --request GET \
#             --header "Content-Type: application/json" \
#             http://localhost:8080/healthz