name: Revive linter

on:
  push:
    branches: [master, dev]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Run Revive Action
      uses: morphy2k/revive-action@v2