name: Linter

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Run Linter
      uses: wearerequired/lint-action@v2
      with:
        gofmt: true