name: S3-env

# only on trunk branch use secrets
on:
  workflow_dispatch:
    inputs:
      aws-account-name:
        description: "AWS Account name"
        required: true
        type: string
      aws-region:
        description: "AWS Region to launch the instance"
        required: true
        type: string
      common-name:
        description: "The name used acrross many resources, usually account-region-project-repo-branch"
        required: true
        type: string
      mongodb-adress:
        description: "The adress of the mongodb instance"
        required: true
        type: string

env:
  AWS_REGION: ${{ inputs.aws-region }}
  COMMON_NAME: ${{ inputs.common-name }}

jobs:

  s3-env:
    name: S3 env
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.aws-account-name }}
    env:
      MONGODB_URI: mongodb://${{ inputs.mongodb-adress }}:27017
      BUCKET_ENV: ${{ inputs.common-name }}-env
      ENV_FILE_NAME: "production.env"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Display non-sensitive variables
        run: |
          printf " \
          ENV_FILE_NAME = $ENV_FILE_NAME\n \
          MONGODB_URI = $MONGODB_URI\n \
          IMAGES_BUCKET = $BUCKET_ENV\n \
          AWS_REGION = $AWS_REGION\n \
          "

      - name: setup AWS CLI
        run: |
          aws --version
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region $AWS_REGION

      - name: Upload env file
        run: |
          cat <<EOF > .env
          MONGODB_URI=$MONGODB_URI
          SCRAPER_DB=scraper
          TAGS_UNDESIRED_COLLECTION=tagsUndesired
          TAGS_DESIRED_COLLECTION=tagsDesired
          PRODUCTION=imagesProduction
          PENDING=imagesPending
          UNDESIRED=imagesUndesired
          VALIDATION=imagesValidation
          USERS_UNDESIRED_COLLECTION=usersUndesired
          IMAGES_BUCKET=$BUCKET_ENV
          FLICKR_PRIVATE_KEY=${{ secrets.FLICKR_PRIVATE_KEY }}
          FLICKR_PUBLIC_KEY=${{ secrets.FLICKR_PUBLIC_KEY }}
          UNSPLASH_PRIVATE_KEY=${{ secrets.UNSPLASH_PRIVATE_KEY }}
          UNSPLASH_PUBLIC_KEY=${{ secrets.UNSPLASH_PUBLIC_KEY }}
          PEXELS_PUBLIC_KEY=${{ secrets.PEXELS_PUBLIC_KEY }}
          ENV=production
          EOF
          aws s3 cp .env s3://$BUCKET_ENV/$ENV_FILE_NAME/$ENV_FILE_NAME